coverage:
  range: 70..100
  round: down
  precision: 1
  status:
    project:
      default:
        target: 90%
        threshold: 0.5%
  ignore:
    - "src/avenir_goals_scenario/_const"
    - "src/avenir_goals_scenario/_import"
    - "src/avenir_goals_scenario/_leapfrog"
