site_name: goals-sa
repo_url: https://github.com/avenirhealth-org/goals-sa
site_url: https://avenirhealth-org.github.io/goals-sa
site_description: Goals scenario analysis
site_author: Rob Ashton
edit_uri: edit/main/docs/
repo_name: avenirhealth-org/goals-sa
copyright: Maintained by <a href="https://www.avenirhealth.org/">Avenir Health</a>.

nav:
  - Home: index.md
  - CLI: cli.md
  - Reference: reference.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            show_root_heading: true
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/avenirhealth-org/goals-sa
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/goals-sa

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
