from pathlib import Path


def find_pjnz_files(pjnz_dir: Path | str) -> list[Path]:
    """Return a sorted list of PJNZ files in a directory.

    Args:
        pjnz_dir: Path to directory to search.

    Returns:
        Sorted list of paths to .PJNZ files.

    Raises:
        FileNotFoundError: If no PJNZ files are found.
    """
    pjnz_dir = Path(pjnz_dir)
    files = sorted(pjnz_dir.glob("*.PJNZ"))
    if not files:
        err_msg = f"No PJNZ files found in {pjnz_dir}"
        raise FileNotFoundError(err_msg)
    return files


def run_scenario_analysis(
    pjnz_dir: Path | str,
    scenarios_path: Path | str,
    output_path: Path | str,
) -> None:
    """Run scenario analysis across a directory of PJNZ files.

    For each combination of PJNZ file and scenario, applies the scenario,
    runs the model, and saves output.

    What output format are we using?

    Args:
        pjnz_dir: Path to directory containing PJNZ files.
        scenarios_path: Path to the scenarios file (generated by generate_scenarios).
        output_path: Path where results will be saved.

    Raises:
        FileNotFoundError: If pjnz_dir or scenarios_path do not exist.
    """
    pjnz_dir = Path(pjnz_dir).resolve()
    scenarios_path = Path(scenarios_path).resolve()
    output_path = Path(output_path).resolve()

    if not pjnz_dir.exists():
        err_msg = f"PJNZ directory does not exist: {pjnz_dir}"
        raise FileNotFoundError(err_msg)
    if not scenarios_path.exists():
        err_msg = f"Scenarios file does not exist: {scenarios_path}"
        raise FileNotFoundError(err_msg)

    pjnz_files = find_pjnz_files(pjnz_dir)

    print(f"Found {len(pjnz_files)} PJNZ files.")

    # TODO: load scenarios from scenarios_path
    # scenarios: list = []

    # TODO: for each pjnz and each scenario, apply the scenario and run goals
    # for pjnz in pjnz_files:
    #     modvars = import_pjnz(pjnz)
    #     for scenario in scenarios:
    #         _run_one(modvars, scenario, output_path)
